on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - name: Usa a action de checkout
        uses: actions/checkout@v3
      - name: Usa a action de setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '12'
      - name: Instalação das dependências
        run: npm install
      - name: Executa o pacote eslint
        run: npx eslint